name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to AWS Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 98.95.177.113
        username: ubuntu
        key: ${{ secrets.DO_SSH_KEY }}
        script: |
          cd /opt/rideshare
          git pull origin main
          npm install --production
          pm2 restart rideshare-analytics

